### PR TITLE
Publish on PyPI via GH Action

### PR DESCRIPTION
**Pull request by thomasmfish**
I have used the logic from ParProcCo for this, but focused on using uv, since this package now uses that.

### CODE REVIEW

**Review by PeterC-DLS — APPROVED** [review]
LGTM

**Comment by thomasmfish** [comment]
Switched to using ruff to match the other PR

**Review by PeterC-DLS — APPROVED** [review]

**Comment by thomasmfish** [comment]
I'm not sure how the upload works -- how is this authorised? Does something need to be done on Diamond's end?

**Comment by PeterC-DLS** [comment]
We use https://docs.pypi.org/trusted-publishers/ and I have configured this project now so all you need once this is merged is to tag it as a release

**Comment by thomasmfish** [comment]
> We use https://docs.pypi.org/trusted-publishers/ and I have configured this project now so all you need once this is merged is to tag it as a release

Great, thank you!

**Pull request merged**
